#==========================================================================#
ARG CUDA=12.8.0
FROM nvidia/cuda:${CUDA}-cudnn-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential \
  python3-full \
  python3-dev \
  python3-pip \
  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

WORKDIR /app
COPY . .
RUN chmod +x src/tools/ANARCI/hmmscan src/tools/voronota/voronota

RUN uv pip install --system .

ENTRYPOINT ["deeprank-ab-predict"]
#==========================================================================#
